config/routes.rb
Rails.application.routes.draw do
  resources :notes
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "notes#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/note.rb
class Note < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: %i[ show edit update destroy ]

  def index
    @notes = Note.all
  end

  def show
  end

  def new
    @note = Note.new
  end

  def edit
  end

  def create
    @note = Note.new(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to note_url(@note), notice: "Note was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to note_url(@note), notice: "Note was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @note.destroy

    respond_to do |format|
      format.html { redirect_to notes_url, notice: "Note was successfully destroyed." }
    end
  end

  private
    def set_note
      @note = Note.find(params[:id])
    end

    def note_params
      params.require(:note).permit(:body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
  require "redcarpet"
  require "rouge"
  require "rouge/plugins/redcarpet"
  
  class RougeHTML < Redcarpet::Render::HTML
    include Rouge::Plugins::Redcarpet
  end
  
  def markdown(text)
    extensions = %i[
        hard_wrap autolink no_intra_emphasis tables fenced_code_blocks
        disable_indented_code_blocks strikethrough lax_spacing space_after_headers
        quote footnotes highlight underline
      ]
    # Markdown.new(text, *extensions).to_html
    Markdown.new(text, *extensions).to_html.html_safe
  end
  
  def advanced_markdown(text)
    render_options = { 
      no_links: false,
      hard_wrap: true,
      link_attributes: { target: '_blank'}
    }
    extensions = {
      disable_indented_code_blocks: true,
      hard_wrap: true,
      autolink: true,
      no_intra_emphasis: true,
      tables: true,
      fenced_code_blocks: true,
      strikethrough: true,
      lax_spacing: true,
      space_after_headers: true,
      quote: true,
      footnotes: true,
      highlight: true,
      underline: true
    }
    # renderer = Redcarpet::Render::HTML.new(render_options)
    renderer = RougeHTML.new(render_options)
    Redcarpet::Markdown.new(renderer, extensions).render(text).html_safe
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MarkdownEditor</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/notes/_form.html.erb
<%= form_with(model: note) do |form| %>
  <% if note.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
        <% note.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body, rows: 30, style: "width: 50%" %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/notes/_note.html.erb
<div id="<%= dom_id note %>">
  <p>
    <strong>Body:</strong>
    <%#= note.body %>
    <%#= simple_format note.body %>
    <%#= markdown note.body %>
    <%= advanced_markdown note.body %>
  </p>

</div>

app/views/notes/edit.html.erb
<h1>Editing note</h1>

<%= render "form", note: @note %>

<br>

<div>
  <%= link_to "Show this note", @note %> |
  <%= link_to "Back to notes", notes_path %>
</div>

app/views/notes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Notes</h1>

<div id="notes">
  <% @notes.each do |note| %>
    <%= render note %>
    <p>
      <%= link_to "Show this note", note %>
    </p>
  <% end %>
</div>

<%= link_to "New note", new_note_path %>

app/views/notes/new.html.erb
<h1>New note</h1>

<%= render "form", note: @note %>

<br>

<div>
  <%= link_to "Back to notes", notes_path %>
</div>

app/views/notes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @note %>

<div>
  <%= link_to "Edit this note", edit_note_path(@note) %> |
  <%= link_to "Back to notes", notes_path %>

  <%= button_to "Destroy this note", @note, method: :delete %>
</div>